### ISSUE TITLE
Modern browsers support

### ISSUE THREAD

**Issue by sashuk** [mobilusoss/react-web-notification#66]
The routine that asks for permissions is expecting the `requestPermission()` to accept callback. However, according to the documentation at https://developer.mozilla.org/en-US/docs/Web/API/Notification/requestPermission the newer standard is returning the Promise.

```
  window.Notification.requestPermission(function (permission) {
    var result = permission === PERMISSION_GRANTED;
    ...
  });
```

Thanks a lot for the library!

**Comment by georgeOsdDev** [comment]
I published v0.8.0 on NPM
https://www.npmjs.com/package/react-web-notification
