### ISSUE TITLE
Web notification error on android

### ISSUE THREAD

**Issue by gabyrusu** [mobilusoss/react-web-notification#70]
After allowing notifications on android browsers, the app is crashing because of this error:

`react-dom.production.min.js:209 TypeError: Failed to construct 'Notification': Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead.`

It seems like this is related to android not supporting the "new Notification()" constructor
https://bugs.chromium.org/p/chromium/issues/detail?id=481856

**Comment by georgeOsdDev** [comment]
Can you try named import like below.
`import * as ReactNotification from 'react-web-notification'`

**Comment by gabyrusu** [comment]
@georgeOsdDev I'm using Typescript so I imported from typings like here
https://github.com/mobilusoss/react-web-notification/issues/38
But that's not the problem as on desktop they work just fine. The problem is on android devices (as tested so far) because they didn't implement the "new Notification()" constructor and might remove it in the future for desktops as well.
See https://bugs.chromium.org/p/chromium/issues/detail?id=481856#c3

**Comment by georgeOsdDev** [comment]
You can use `props.swRegistration`.
It will not call `new Notification()`.

**Comment by gabyrusu** [comment]
Oh, how did I missed that? Thanks!
