### ISSUE TITLE
how schedule a notification?

### ISSUE THREAD

**Issue by MedinaGitHub** [mobilusoss/react-web-notification#78]
for example schedule notification to 3 days more at 13:30

Thanks you!

**Comment by georgeOsdDev** [comment]
This library is wrapper for [Notification API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API)
You need to develop scheduling logic by yourself using `setTimeout` etc.

I think you should consider to use [Push API](https://developer.mozilla.org/en-US/docs/Web/API/Push_API).
